# Practical 4: Eigenvalues and Eigenvectors

### Eigenvalues & Eigenvectors of a Square Matrix

In [2]:
import numpy as np
# Define square matrix A
A = np.array([[2,0,1],[-1,4,-1],[-1,2,0]])
print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: \n", eigvecs)

[[ 2  0  1]
 [-1  4 -1]
 [-1  2  0]]
Eigenvalues are:  [3. 2. 1.]
Eigenvectors are: 
 [[ 4.08248290e-01  8.94427191e-01 -7.07106781e-01]
 [ 8.16496581e-01  4.47213595e-01 -8.72620868e-17]
 [ 4.08248290e-01 -4.12775854e-16  7.07106781e-01]]


So the eigenvalues of A are: 3, 2, and 1
Notice that the corresponding eigenvectors are given in columns and are 
normalized to unit length.

In [3]:
# The first eigenvalue is 3
# Its corresponding eigenvector is in column 1 of eigvecs
print("First eigenvalue is: ", eigvals[0])# subject to rounding errors
print("Corresponding eigenvector is: ", eigvecs[:,0])
print("Its magnitude is: ", np.linalg.norm(eigvecs[:,0])) # subject to rounding error


First eigenvalue is:  3.0
Corresponding eigenvector is:  [0.40824829 0.81649658 0.40824829]
Its magnitude is:  1.0


To check whether the first vector and first value are indeed the eigenvector and eigenvalue
of A, we do the following:

In [4]:
# Find Av
B = np.dot(A, eigvecs[:,0])
print("Av is: ", B)

# Find lambda*v
C = eigvals[0]* eigvecs[:,0]
print("lambda*v is: ", C)


Av is:  [1.22474487 2.44948974 1.22474487]
lambda*v is:  [1.22474487 2.44948974 1.22474487]


Notice that the two answers are the same, confirming that the first vector is an eigenvector
corresponding to the first eigenvalue. 

### Task 1

Some properties of eigenvalues include:<br> 
•	The sum of eigenvalues of a matrix equals its trace.<br>
•	The product of eigenvalues equals its determinant.<br><br>
Verify the properties above using the matrix $\mathbf{A}=\begin{bmatrix}2 & 1 & 2 \\ 2 & 2 & -2 \\ 3 & 1 & 1 \end{bmatrix}$

In [5]:
A = np.array([[2,1,2],[2,2,-2],[3,1,1]])
print("sum of Eigenvalues are: ", sum(np.linalg.eig(A)[0]) )
print("Trace of A is: ",np.trace(A))

print("Products of eigenvalues: ",np.prod(np.linalg.eig(A)[0]))
print("det(A): ", np.linalg.det(A) )

sum of Eigenvalues are:  5.0000000000000036
Trace of A is:  5
Products of eigenvalues:  -7.9999999999999964
det(A):  -8.000000000000002


### Task 2

**Symmetric Matrix**: The eigenvalues of a symmetrical matrix are always real and the eigenvectors are always orthogonal. Verify this in Python for the matrix A below.<br>
$$\mathbf{A}=\begin{bmatrix}1 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 1 \end{bmatrix}$$

In [6]:
A = np.array([[1,-1,0],[-1,2,-1],[0,-1,1]])

print(A)
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: \n", eigvecs)



[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]
Eigenvalues are:  [ 3.00000000e+00  1.00000000e+00 -5.13860489e-17]
Eigenvectors are: 
 [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  2.48915666e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]


In [7]:
v1 = np.array([[-4.08248290e-01],[8.16496581e-01],[-4.08248290e-01]])
v2 = np.array([[-7.07106781e-01],[2.48915666e-16],[7.07106781e-01]])
v3 = np.array([[5.77350269e-01],[5.77350269e-01],[5.77350269e-01]])

In [8]:
print(np.dot(v1.T,v3))

[[5.77350223e-10]]
