In [4]:
import numpy as np
np.set_printoptions(suppress=True)
# convert to row echelon form
A = np.array([[1, 1, 1], [20, 30, 16], [2.4, 1.9, 1.8]], dtype='float')
b = np.array([10, 200, 20])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)
print(Ab)
#Converts augmented matrix to row echelon form
for i in range(n):
    ############ MODIFICATION START #############
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i,i] == 0:
        temp = Ab[i].copy()

        for k in range (i + 1, n):
            if Ab[k, i] != 0:
                Ab[i] = Ab[k].copy()
                Ab[k] = temp.copy()
                break
    ############ MODIFICATION END #############
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

print(Ab)

# answer output
x = Ab[:, n]
x

for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

print(Ab)

# answer output
x = Ab[:, n]
x

[[  1.    1.    1.   10. ]
 [ 20.   30.   16.  200. ]
 [  2.4   1.9   1.8  20. ]]
[[ 1.   1.   1.  10. ]
 [ 0.  10.  -4.   0. ]
 [ 0.   0.  -0.8 -4. ]]
[[ 1. -0. -0.  3.]
 [ 0.  1.  0.  2.]
 [-0. -0.  1.  5.]]


array([3., 2., 5.])

In [39]:
A = np.array(([2,4],[1,5]))
B = np.array(([0,1],[-1,6]))
C = np.array(([-2,3],[1,5]))
Y = A-np.transpose(B)
ans = A+np.dot(np.transpose(B),C)
print(ans)

print(np.linalg.inv(B))

[[ 1 -1]
 [ 5 38]]
[[ 6. -1.]
 [ 1.  0.]]


In [66]:
import numpy as np

data = np.array(([10,40],[11,45],[15,53]))
display(data)
x_bar = np.mean(data, axis=0)
print(x_bar)

print(np.dot(1/3*np.transpose(data),(np.ones(3))))

print(np.cov(data, rowvar=0))
print(np.corrcoef(data, rowvar=0))
print(np.linalg.det(np.cov(data, rowvar=0)))

array([[10, 40],
       [11, 45],
       [15, 53]])

[12. 46.]
[12. 46.]
[[ 7. 17.]
 [17. 43.]]
[[1.         0.97986371]
 [0.97986371 1.        ]]
11.999999999999984


In [41]:
import numpy as np
import pandas as pd
eigvals, eigvecs = np.linalg.eig(np.cov(data, rowvar=0))


print(eigvals,eigvecs)
print(eigvals.shape)
eigvals_df = pd.DataFrame(np.round(np.transpose(eigvals),4),columns=['Eigenvalues'])
eigvals_df.index = ['PC{}'.format(i) for i in range(1,len(eigvals_df)+1)]
display(eigvals_df)
# Put the eigenvectors into a dataframe
eigvecs_df = pd.DataFrame(np.round(np.transpose(eigvecs),4),columns=['Eigenvalues'])
eigvecs_df.index = ['PC{}'.format(i) for i in range(1,len(eigvecs_df)+1)]
display(eigvecs_df)

[ 0.24116319 49.75883681] [[-0.92925055 -0.36945016]
 [ 0.36945016 -0.92925055]]
(2,)


Eigenvalues
PC1       0.2412
PC2      49.7588

ValueError: Shape of passed values is (2, 2), indices imply (2, 1)

In [ ]:
A = np.array(([0,2,-1],[-2,7,-2],[-5,14,-4]))

A = A-np.eye(3)
print(A)
# convert to row echelon form
b = np.array([0, 0, 0])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)

#Converts augmented matrix to row echelon form
for i in range(n):
    ############ MODIFICATION START #############
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i,i] == 0:
        temp = Ab[i].copy()

        for k in range (i + 1, n):
            if Ab[k, i] != 0:
                Ab[i] = Ab[k].copy()
                Ab[k] = temp.copy()
                break
    ############ MODIFICATION END #############
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

print(Ab)

# answer output
x = Ab[:, n]

x


In [ ]:
C = np.array(([4,3],[7,2]))
print(np.linalg.inv(C))

In [5]:
import numpy as np
# convert to row echelon form
A = np.array([[75, 55, 30], [0, 4, 9], [0, 280, 30]], dtype='float')
b = np.array([870000, 171000, 870000])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)

#Converts augmented matrix to row echelon form
for i in range(n):
    ############ MODIFICATION START #############
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i, i] == 0:
        temp = Ab[i].copy()

        for k in range(i + 1, n):
            if Ab[k, i] != 0:
                Ab[i] = Ab[k].copy()
                Ab[k] = temp.copy()
                break
    ############ MODIFICATION END #############
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

print(Ab)

# answer output
x = Ab[:, n]
x
#Converts FROM row echelon form to reduced row echelon form
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

print(Ab)

# answer output
x = Ab[:, n]
x

[[       75.        55.        30.    870000.]
 [        0.         4.         9.    171000.]
 [        0.         0.      -600. -11100000.]]
[[    1.    -0.    -0.  3375.]
 [    0.     1.    -0.  1125.]
 [   -0.    -0.     1. 18500.]]


array([ 3375.,  1125., 18500.])

In [49]:
data = np.array(([10,40],[11,45],[15,53]))


#Find sample correlation matrix

R = np.corrcoef(data, rowvar=0)
display(R)

array([[1.        , 0.97986371],
       [0.97986371, 1.        ]])

In [48]:
import numpy as np
import pandas as pd
A = np.array(([1,-1,1],[3,-3,1],[3,-5,3]))

b = np.array(([0],[0],[0]))
A = A-np.eye(3)
display(A)
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)

#Converts augmented matrix to row echelon form
for i in range(n):
    ############ MODIFICATION START #############
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i,i] == 0:
        temp = Ab[i].copy()

        for k in range (i + 1, n):
            if Ab[k, i] != 0:
                Ab[i] = Ab[k].copy()
                Ab[k] = temp.copy()
                break
    ############ MODIFICATION END #############
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

print(Ab)

# answer output
x = Ab[:, n]

x


array([[ 0., -1.,  1.],
       [ 3., -4.,  1.],
       [ 3., -5.,  2.]])

[[ 3. -4.  1.  0.]
 [ 0. -1.  1.  0.]
 [ 0.  0.  0.  0.]]


array([0., 0., 0.])

In [62]:
vector = np.array(([1,0,1],[1,1,1],[2,1,1]))


A = np.array(([1,-1,1],[3,-3,1],[3,-5,3]))
B = np.array(([1,-1,1],[3,-3,1],[3,-5,3]))
mul = np.dot(A,A)
mul = np.dot(mul,B)
arr = np.array(([1],[2],[3]))
final = np.dot(mul,arr)
print(final)

[[8]
 [0]
 [8]]


In [69]:
# convert to row echelon form
A = np.array([[1, 2, -1], [0, 1, 2], [0, -2, 1]], dtype='float')
b = np.array([-3, 3, 4])
Ab = np.hstack([A, b.reshape(-1, 1)])
n = len(b)
print(Ab)
#Converts augmented matrix to row echelon form
for i in range(n):
    ############ MODIFICATION START #############
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i,i] == 0:
        temp = Ab[i].copy()

        for k in range (i + 1, n):
            if Ab[k, i] != 0:
                Ab[i] = Ab[k].copy()
                Ab[k] = temp.copy()
                break
    ############ MODIFICATION END #############
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

print(Ab)

# answer output
x = Ab[:, n]
x
#Converts FROM row echelon form to reduced row echelon form
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

print(Ab)

# answer output
x = Ab[:, n]
x

[[ 1.  2. -1. -3.]
 [ 0.  1.  2.  3.]
 [ 0. -2.  1.  4.]]
[[ 1.  2. -1. -3.]
 [ 0.  1.  2.  3.]
 [ 0.  0.  5. 10.]]
[[ 1. -0.  0.  1.]
 [-0.  1. -0. -1.]
 [ 0.  0.  1.  2.]]


array([ 1., -1.,  2.])

In [77]:
C = np.array(([4,3],[7,2]))
print(C)
det = np.linalg.inv(C)
print(det)

[[4 3]
 [7 2]]
[[-0.15384615  0.23076923]
 [ 0.53846154 -0.30769231]]
