In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets
pd.set_option('display.max_rows', 500)


# Data Loading and Preparation

In [9]:
iris = datasets.load_iris()
df1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])
display(df1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
30                 4.8               3.1                1.6               0.2   
31                 5.4               3.4                1.5               0.4   
32                 5.2               4.1                1.5               0.1   
33                 5.5               4.2                1.4               0.2   
34                 4.9               3.1                1.5               0.2   
35                 5.0               3.2                1.2               0.2   
36                 5.5               3.5                1.3               0.2   
37                 4.9               3.6                1.4               0.1   
38                 4.4               3.0                1.3               0.2   
39                 5.1               3.4                1.5               0.2   
40                 5.0               3.5                1.3               0.3   
41                 4.5               2.3                1.3               0.3   
42                 4.4               3.2                1.3               0.2   
43                 5.0               3.5                1.6               0.6   
44                 5.1               3.8                1.9               0.4   
45                 4.8               3.0                1.4               0.3   
46                 5.1               3.8                1.6               0.2   
47                 4.6               3.2                1.4               0.2   
48                 5.3              

In [4]:
# get the data (X) and target (y)
X,y = iris.data, iris.target
# split the dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)


# Modelling

1. Train the model Features (`X_train`) with Train Labels (`y_train`)
2. Score the model using test features (`X_test`) and test labels (`y_test`)
3. Evaluate the results of model using Confusion Matrix

In [5]:
# get the LogisticRegression estimator
from sklearn.linear_model import LogisticRegression

# training the model
# apply algorithm  to data using fit()
clf = LogisticRegression(solver='newton-cg',multi_class='multinomial')
# train the model with the features (X_train) and labels (y_train)
clf.fit(X_train,y_train)


LogisticRegression(multi_class='multinomial', solver='newton-cg')

In [6]:
# We can save the trained model clf using pickle (step 4)
import pickle
s = pickle.dumps(clf)
pickle.dump( clf, open( "iris_trained_model.p", "wb" ) )
clf2 = pickle.load( open( "iris_trained_model.p", "rb" ) )



In [7]:
# Score the model (step 5)
y_hat = clf.predict(X_test)

# Evaluation of the model (step 6)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_hat)
print(cm)


[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]
