In [16]:
import numpy as np
np.set_printoptions(suppress=True)

cov = (np.cov([[4,1], [-1, 3],[3,5]]))

eigvals, eigvecs=np.linalg.eig (cov)#Get eigenvalues&eigenvectors
print (eigvals)
print('\n')
print (eigvecs)

[14.5  0.  -0. ]


[[-0.55708601  0.         -0.82728901]
 [ 0.74278135 -0.4472136  -0.53538547]
 [ 0.37139068  0.89442719 -0.17016258]]
