# Practical 1: Vectors & Matrices


Many machine learning algorithms make use of matrices to store and process data. 
For example, a deep learning algorithm makes use of matrices to store inputs such as 
images, tweets, or text to solve problems. An artificial neural network makes use of 
matrices to store information such as weights during training. A familiarity with 
matrices and vectors is hence important.

In this practical we will learn some of the fundamentals of matrices and vectors.

A **vector** can be represented as a list in Python.
For example:

In [ ]:
v = [ 1, 4, 2]
print(v)

A **matrix** is a 2D array which stores numbers. 
Alternatively, a matrix can also be thought of as 
a list of vectors.

An example:

In [1]:
A = [[1,4,2],[0,6,3],[3,5,6]]
print(A)

[[1, 4, 2], [0, 6, 3], [3, 5, 6]]


An alternative way to work with vectors and matrices is
to use the **NumPy** module in Python.

In [2]:
import numpy as np
v = np.array([[1],
               [4],
               [2]])
print(v)
A = np.array([[1,4, 2], [0, 6, 3],[3, 5, 6]])
print(A)

[[1]
 [4]
 [2]]
[[1 4 2]
 [0 6 3]
 [3 5 6]]


We can check the order of **A** and **v** as follows:

In [3]:
print("A if of dimension: ", A.shape)
print("v is of dimension: ", v.shape)

A if of dimension:  (3, 3)
v is of dimension:  (3, 1)


There are a lot of matrix operations which we can make use
of in **NumPy**. Some examples are given below.

In [5]:
# Matrix Addition
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = A+B
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[ 8 10]
 [10  8]]


In [6]:
# Matrix Subtraction
D = A - B
print(D)

[[ 2  6]
 [ 2 10]]


In [7]:
# Matrix-Scalar Multiplication
A = np.array([[5,8],[6,9]])
print(A)
b = 2
E = A*2

print(E)

[[5 8]
 [6 9]]
[[10 16]
 [12 18]]


In [8]:
# Matrix-Vector Multiplication
A = np.array([[5,8],[6,9]])
print(A)
v = np.array([[1],[4]])
print(v)
w = np.dot(A,v)
print(w)

[[5 8]
 [6 9]]
[[1]
 [4]]
[[37]
 [42]]


In [9]:
# Matrix-Matrix Multiplication
A = np.array([[5,8],[6,9]])
print(A)
B = np.array([[3,2],[4,-1]])
print(B)
C = np.dot(A,B)
print(C)

[[5 8]
 [6 9]]
[[ 3  2]
 [ 4 -1]]
[[47  2]
 [54  3]]


In [ ]:
# Taking transpose
print(A)
B = A.T
print(B)

In [ ]:
# Finding trace
print(A)
traceA = np.trace(A)
print(traceA)

In [ ]:
# Finding Matrix Determinant
A = np.array([[5,8],[6,9]])
print(A)
detA = np.linalg.det(A)
print(detA)

In [ ]:
# Matrix Inverse
print(A)
B = np.linalg.inv(A)
print(B)

An **identity matrix** of order 3 can be created as follows:

In [ ]:
I3 = np.eye(3)
print(I3)

To create a 2x3 matrix of random numbers drawn from a normal distribution with mean 0 and variance 1, we use:

In [10]:
weights = np.random.randn(2,3)
print(weights)

[[ 0.21711581 -0.2378506   0.22618996]
 [-0.92223301  1.27091888 -0.26891581]]


A 3x3 **diagonal matrix** with (1, 5, 1) along its principal diagonal can be constructed as follows:

In [11]:
A = np.diag((1, 5, 1))
print(A)

[[1 0 0]
 [0 5 0]
 [0 0 1]]


To create a 1x3 matrix of **ones**, we can do as follows:

In [3]:
print(np.ones((1,3)))

[[1. 1. 1.]]


In [2]:
import numpy as np

### Task 1
Enter the matrix $\mathbf{A}=\begin{bmatrix}1 & 2 & 4 & 5 \\ 0 & 1 & 5 & -2 \\ 2 & -4 & 3 & 9 \end{bmatrix}$ in Python.<br>
Display the following: <br>
(a)  the size of the matrix $\mathbf{A}$ <br>
(b)  $a_{23}$, $a_{32}$ and $a_{34}$ <br>
(c)  row 1 and column 4 of $\mathbf{A}$

In [8]:
A = np.array([[1,2,4,5], [0,1,5,-2],[2, -4, 3 , 9]])
print(A.shape)

(3, 4)


In [19]:
#a23
print("a23:",A[1][2])
#a32
print("a32:",A[2][1])
#a34
print("a34:",A[2][3])

a23: 5
a32: -4
a34: 9


In [4]:
#row 1
print(A[0])
#column 4
print(A[:,3])

[1 2 4 5]
[ 5 -2  9]


### Task 2
Enter the following matrices in Python. <br>
$\mathbf{A}=\begin{bmatrix}7 & -3 \\ 2 & 1 \\ 9 & -6 \\ -3 & 2 \end{bmatrix} , 
\mathbf{B}=\begin{bmatrix}2 \\ 5 \end{bmatrix} , 
\mathbf{C}=\begin{bmatrix}5 & 1 & -8 & 4 \\ 2 & 7 & -3 & 5\end{bmatrix}$ <br>
Compute each of the following expression if possible. <br>
(a) $\mathbf{AC}$ <br>
(b) $\mathbf{AB}$ <br>
(c) $\mathbf{A} + \mathbf{C}^T$ <br>
(d) $\mathbf{BA}$ <br>
(e) $\mathbf{AA}^T + \mathbf{C}^T\mathbf{C}$ <br>
(f) $\mathbf{A} + 2\mathbf{C}^T$

In [11]:
A = np.array([[7,-3],
             [2, 1],
             [9,-6],
             [-3, 2]])
B = np.array([[2],
            [5]])
C = np.array([[5, 1, -8, 4],
            [2, 7 ,-3, 5]])

In [15]:
#a 
print("AC= ")
print(np.dot(A, C))

AC= 
[[ 29 -14 -47  13]
 [ 12   9 -19  13]
 [ 33 -33 -54   6]
 [-11  11  18  -2]]


In [16]:
#b
print("AB= ")
print(np.dot(A,B))

AB= 
[[ -1]
 [  9]
 [-12]
 [  4]]


In [26]:
#c
print("A+𝐂𝑇= ")
print(A+C.T)

A+𝐂𝑇= 
[[12 -1]
 [ 3  8]
 [ 1 -9]
 [ 1  7]]


In [27]:
#d
print("BA = ")
print(np.dot(B,A))

BA = 


ValueError: shapes (2,1) and (4,2) not aligned: 1 (dim 1) != 4 (dim 0)

In [28]:
#e
print("𝐀𝐀𝑇+𝐂𝑇𝐂 = ")
print(np.dot(A,A.T)+np.dot(C.T, C))

𝐀𝐀𝑇+𝐂𝑇𝐂 = 
[[ 87  30  35   3]
 [ 30  55 -17  35]
 [ 35 -17 190 -86]
 [  3  35 -86  54]]


In [29]:
#f
print("𝐀+2𝐂𝑇=")
print(A+(C.T*2))

𝐀+2𝐂𝑇=
[[ 17   1]
 [  4  15]
 [ -7 -12]
 [  5  12]]


### Task 3
Determine if each of the following matrices is singular.<br>
(a) $\mathbf{A}=\begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}0 & 1 & 3 & 4 \\ -2 & 1 & 2 & 1 \\ 2 & 0 & 1 & 0 \\ 0 & 8 & 3 & 1 \end{bmatrix}$ <br>

In [36]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(f'det(A) is {np.linalg.det(A)}, which is 0. Hence A is singular')

det(A) is -9.51619735392994e-16, which is 0. Hence A is singular


In [34]:
A = np.array([[0,1,3,4],
            [-2,1,2,1],
            [2,0,1,0],
            [0,8,3,1]])
print(f'det(A) is {np.linalg.det(A)}, which is not 0. Hence A is non-singular')

det(A) is -126.0, which is not 0. Hence A is non-singular


### Task 4
Find the inverse of each matrix.<br>
(a) $\mathbf{A}=\begin{bmatrix}2 & 1 \\ 3 & 5 \end{bmatrix}$ <br><br>
(b) $\mathbf{A}=\begin{bmatrix}1 & 1 & 2 \\ 2 & 1 & 1 \\ 1 & 2 & 1 \end{bmatrix}$

In [39]:
A = np.array([[2,1],
             [3,5]])

In [40]:
print(np.linalg.inv(A))

[[ 0.71428571 -0.14285714]
 [-0.42857143  0.28571429]]


In [41]:
A = np.array([[1,1,2],
             [2,1,1],
             [1,2,1]])

In [42]:
print(np.linalg.inv(A))

[[-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]
 [ 0.75 -0.25 -0.25]]


### Task 5
Determine the norm of each of the following vectors.<br>
(a) $\mathbf{v}_1=\begin{bmatrix}2 \\ -1 \\ 1 \end{bmatrix}$ <br><br>
(b) $\mathbf{v}_2=\begin{bmatrix}4 \\ 0 \\ 3 \\ -1 \end{bmatrix}$ <br><br>
(c) $\mathbf{v}_3=\begin{bmatrix}1 \\ 0 \\ 2 \\ 2 \\ 3 \end{bmatrix}$

In [43]:
v1 = np.array([[2],[-1],[1]])
print(np.linalg.norm(v1))

2.449489742783178


In [44]:
v2 = np.array([[4],[0],[-3],[-1]])
print(np.linalg.norm(v2))

5.0990195135927845


In [45]:
v3 = np.array([[1],[0],[2],[2],[3]])
print(np.linalg.norm(v3))

4.242640687119285
