In [1]:
import numpy as np

In [3]:
A=np.array([[1,-2],[3,2]])
print(A)

[[ 1 -2]
 [ 3  2]]


In [4]:
B=np.array([[3,7,1],[2,5,0],[4,0,8]])
print(B)

[[3 7 1]
 [2 5 0]
 [4 0 8]]


In [5]:
Ain= np.linalg.inv(A)
print(Ain)

[[ 0.25   0.25 ]
 [-0.375  0.125]]


In [7]:
Bin = np.linalg.inv(B)
print(Bin)

[[-3.33333333  4.66666667  0.41666667]
 [ 1.33333333 -1.66666667 -0.16666667]
 [ 1.66666667 -2.33333333 -0.08333333]]
